# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data/models/player.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x61ta/models/player.proto\x12\x07players\"\xd3\x01\n\x06Player\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x13\n\x0bplayer_name\x18\x02 \x01(\t\x12\x13\n\x0bprofile_url\x18\x03 \x01(\t\x12\x10\n\x08position\x18\x04 \x01(\t\x12\x0e\n\x06rating\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x12\n\nhighschool\x18\x07 \x01(\t\x12\x0e\n\x06height\x18\x08 \x01(\t\x12\x0e\n\x06weight\x18\t \x01(\t\x12\x12\n\nold_school\x18\n \x01(\t\x12\x12\n\nnew_school\x18\x0b \x01(\t\"\xc7\x02\n\x11PlayerSeasonStats\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x13\n\x0bseason_year\x18\x02 \x01(\t\x12\x14\n\x0cgames_played\x18\x03 \x01(\x05\x12\x16\n\x0eminutes_played\x18\x04 \x01(\x02\x12\x17\n\x0fpoints_per_game\x18\x05 \x01(\x02\x12\x19\n\x11rebounds_per_game\x18\x06 \x01(\x02\x12\x18\n\x10\x61ssists_per_game\x18\x07 \x01(\x02\x12\x17\n\x0f\x62locks_per_game\x18\x08 \x01(\x02\x12\x17\n\x0fsteals_per_game\x18\t \x01(\x02\x12\x1d\n\x15\x66ield_goal_percentage\x18\n \x01(\x02\x12\x1e\n\x16three_point_percentage\x18\x0b \x01(\x02\x12\x1d\n\x15\x66ree_throw_percentage\x18\x0c \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data.models.player_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYER._serialized_start=38
  _PLAYER._serialized_end=249
  _PLAYERSEASONSTATS._serialized_start=252
  _PLAYERSEASONSTATS._serialized_end=579
# @@protoc_insertion_point(module_scope)
