// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: data/models/player.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single player's static information
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	ProfileUrl    string                 `protobuf:"bytes,3,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Rating        string                 `protobuf:"bytes,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Highschool    string                 `protobuf:"bytes,7,opt,name=highschool,proto3" json:"highschool,omitempty"`
	Height        string                 `protobuf:"bytes,8,opt,name=height,proto3" json:"height,omitempty"`
	Weight        string                 `protobuf:"bytes,9,opt,name=weight,proto3" json:"weight,omitempty"`
	OldSchool     string                 `protobuf:"bytes,10,opt,name=old_school,json=oldSchool,proto3" json:"old_school,omitempty"`
	NewSchool     string                 `protobuf:"bytes,11,opt,name=new_school,json=newSchool,proto3" json:"new_school,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_data_models_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_data_models_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_data_models_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *Player) GetProfileUrl() string {
	if x != nil {
		return x.ProfileUrl
	}
	return ""
}

func (x *Player) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Player) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *Player) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Player) GetHighschool() string {
	if x != nil {
		return x.Highschool
	}
	return ""
}

func (x *Player) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *Player) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *Player) GetOldSchool() string {
	if x != nil {
		return x.OldSchool
	}
	return ""
}

func (x *Player) GetNewSchool() string {
	if x != nil {
		return x.NewSchool
	}
	return ""
}

// Statistical data for a single season
type PlayerSeasonStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PlayerId             string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SeasonYear           string                 `protobuf:"bytes,2,opt,name=season_year,json=seasonYear,proto3" json:"season_year,omitempty"`
	GamesPlayed          int32                  `protobuf:"varint,3,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	MinutesPlayed        float32                `protobuf:"fixed32,4,opt,name=minutes_played,json=minutesPlayed,proto3" json:"minutes_played,omitempty"`
	PointsPerGame        float32                `protobuf:"fixed32,5,opt,name=points_per_game,json=pointsPerGame,proto3" json:"points_per_game,omitempty"`
	ReboundsPerGame      float32                `protobuf:"fixed32,6,opt,name=rebounds_per_game,json=reboundsPerGame,proto3" json:"rebounds_per_game,omitempty"`
	AssistsPerGame       float32                `protobuf:"fixed32,7,opt,name=assists_per_game,json=assistsPerGame,proto3" json:"assists_per_game,omitempty"`
	BlocksPerGame        float32                `protobuf:"fixed32,8,opt,name=blocks_per_game,json=blocksPerGame,proto3" json:"blocks_per_game,omitempty"`
	StealsPerGame        float32                `protobuf:"fixed32,9,opt,name=steals_per_game,json=stealsPerGame,proto3" json:"steals_per_game,omitempty"`
	FieldGoalPercentage  float32                `protobuf:"fixed32,10,opt,name=field_goal_percentage,json=fieldGoalPercentage,proto3" json:"field_goal_percentage,omitempty"`
	ThreePointPercentage float32                `protobuf:"fixed32,11,opt,name=three_point_percentage,json=threePointPercentage,proto3" json:"three_point_percentage,omitempty"`
	FreeThrowPercentage  float32                `protobuf:"fixed32,12,opt,name=free_throw_percentage,json=freeThrowPercentage,proto3" json:"free_throw_percentage,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlayerSeasonStats) Reset() {
	*x = PlayerSeasonStats{}
	mi := &file_data_models_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSeasonStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSeasonStats) ProtoMessage() {}

func (x *PlayerSeasonStats) ProtoReflect() protoreflect.Message {
	mi := &file_data_models_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSeasonStats.ProtoReflect.Descriptor instead.
func (*PlayerSeasonStats) Descriptor() ([]byte, []int) {
	return file_data_models_player_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerSeasonStats) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerSeasonStats) GetSeasonYear() string {
	if x != nil {
		return x.SeasonYear
	}
	return ""
}

func (x *PlayerSeasonStats) GetGamesPlayed() int32 {
	if x != nil {
		return x.GamesPlayed
	}
	return 0
}

func (x *PlayerSeasonStats) GetMinutesPlayed() float32 {
	if x != nil {
		return x.MinutesPlayed
	}
	return 0
}

func (x *PlayerSeasonStats) GetPointsPerGame() float32 {
	if x != nil {
		return x.PointsPerGame
	}
	return 0
}

func (x *PlayerSeasonStats) GetReboundsPerGame() float32 {
	if x != nil {
		return x.ReboundsPerGame
	}
	return 0
}

func (x *PlayerSeasonStats) GetAssistsPerGame() float32 {
	if x != nil {
		return x.AssistsPerGame
	}
	return 0
}

func (x *PlayerSeasonStats) GetBlocksPerGame() float32 {
	if x != nil {
		return x.BlocksPerGame
	}
	return 0
}

func (x *PlayerSeasonStats) GetStealsPerGame() float32 {
	if x != nil {
		return x.StealsPerGame
	}
	return 0
}

func (x *PlayerSeasonStats) GetFieldGoalPercentage() float32 {
	if x != nil {
		return x.FieldGoalPercentage
	}
	return 0
}

func (x *PlayerSeasonStats) GetThreePointPercentage() float32 {
	if x != nil {
		return x.ThreePointPercentage
	}
	return 0
}

func (x *PlayerSeasonStats) GetFreeThrowPercentage() float32 {
	if x != nil {
		return x.FreeThrowPercentage
	}
	return 0
}

var File_data_models_player_proto protoreflect.FileDescriptor

const file_data_models_player_proto_rawDesc = "" +
	"\n" +
	"\x18data/models/player.proto\x12\aplayers\"\xc1\x02\n" +
	"\x06Player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x1f\n" +
	"\vprofile_url\x18\x03 \x01(\tR\n" +
	"profileUrl\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\tR\x06rating\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"highschool\x18\a \x01(\tR\n" +
	"highschool\x12\x16\n" +
	"\x06height\x18\b \x01(\tR\x06height\x12\x16\n" +
	"\x06weight\x18\t \x01(\tR\x06weight\x12\x1d\n" +
	"\n" +
	"old_school\x18\n" +
	" \x01(\tR\toldSchool\x12\x1d\n" +
	"\n" +
	"new_school\x18\v \x01(\tR\tnewSchool\"\x87\x04\n" +
	"\x11PlayerSeasonStats\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vseason_year\x18\x02 \x01(\tR\n" +
	"seasonYear\x12!\n" +
	"\fgames_played\x18\x03 \x01(\x05R\vgamesPlayed\x12%\n" +
	"\x0eminutes_played\x18\x04 \x01(\x02R\rminutesPlayed\x12&\n" +
	"\x0fpoints_per_game\x18\x05 \x01(\x02R\rpointsPerGame\x12*\n" +
	"\x11rebounds_per_game\x18\x06 \x01(\x02R\x0freboundsPerGame\x12(\n" +
	"\x10assists_per_game\x18\a \x01(\x02R\x0eassistsPerGame\x12&\n" +
	"\x0fblocks_per_game\x18\b \x01(\x02R\rblocksPerGame\x12&\n" +
	"\x0fsteals_per_game\x18\t \x01(\x02R\rstealsPerGame\x122\n" +
	"\x15field_goal_percentage\x18\n" +
	" \x01(\x02R\x13fieldGoalPercentage\x124\n" +
	"\x16three_point_percentage\x18\v \x01(\x02R\x14threePointPercentage\x122\n" +
	"\x15free_throw_percentage\x18\f \x01(\x02R\x13freeThrowPercentageB\x1eZ\x1cnilytics/app/api/internal/pbb\x06proto3"

var (
	file_data_models_player_proto_rawDescOnce sync.Once
	file_data_models_player_proto_rawDescData []byte
)

func file_data_models_player_proto_rawDescGZIP() []byte {
	file_data_models_player_proto_rawDescOnce.Do(func() {
		file_data_models_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_models_player_proto_rawDesc), len(file_data_models_player_proto_rawDesc)))
	})
	return file_data_models_player_proto_rawDescData
}

var file_data_models_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_models_player_proto_goTypes = []any{
	(*Player)(nil),            // 0: players.Player
	(*PlayerSeasonStats)(nil), // 1: players.PlayerSeasonStats
}
var file_data_models_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_models_player_proto_init() }
func file_data_models_player_proto_init() {
	if File_data_models_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_models_player_proto_rawDesc), len(file_data_models_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_models_player_proto_goTypes,
		DependencyIndexes: file_data_models_player_proto_depIdxs,
		MessageInfos:      file_data_models_player_proto_msgTypes,
	}.Build()
	File_data_models_player_proto = out.File
	file_data_models_player_proto_goTypes = nil
	file_data_models_player_proto_depIdxs = nil
}
